### PR TITLE
Support x-ray-parse filters

### PR DESCRIPTION
**Pull request by fabien**
I noticed that x-ray-parse supports the notion of filters. This PR enables this functionality in Xray.

### CODE REVIEW

**Comment by Kikobeats** [comment]
Hey,

It looks good. This afternoon I'm going to fix codebase test. Also consider add specific tests for this feature to be sure that all is ok!

**Comment by fabien** [comment]
Thanks! I've added a basic test - would be nice to have the other (commented out) tests working again, too. Looking forward to your 2.1 release!

**Comment by Kikobeats** [comment]
I merged my branch; consider prepare for the next build 😃

**Comment by fabien** [comment]
@Kikobeats great! Do you want me to fix any merge conflicts, so you can handle this PR?

**Comment by fabien** [comment]
@Kikobeats do you want me to resolve these conflicts so you can pull?

**Comment by Kikobeats** [comment]
@fabien yes! how many conflicts do you have? maybe we can resolve it here?

**Comment by fabien** [comment]
Superseded by: https://github.com/lapwinglabs/x-ray/pull/169

/cc @Kikobeats

**Pull request closed without merging**
