### PR TITLE
          // Nested crawling broken on 'master'.

### PR DESCRIPTION
**Pull request by Muscot**
### Description

I think I fixed this issue, I also added a follow.js example to test. 
Nested crawling broken on 'master'. When to merge 'bugfix/nested-crawling' #111

          // Needed to exit this without calling next, the problem was that it returned to 
          // the "finished" callback before it had retrieved all pending request. it should
          // wait for "return next(null, compact(out))"

x('http://www.imdb.com/', {
    title: ['title'],
    links: x('.rhs-body .rhs-row', [{
        text: 'a',
        href: 'a@href',
        next_page: x('a@href', {
          title: 'title',
          heading: 'h1'
        })
    }])
})(function(err, obj) {
    console.log(obj);
});

### Checklist

- [X] Code compiles correctly
- [X] Created tests which fail without the change (if possible)
- [ ] All tests passing
- [ ] Extended the README / documentation, if necessary
- [ ] Added myself / the copyright holder to the AUTHORS file

### CODE REVIEW

**Comment by mcornella** [comment]
Adding the `return` statement works for me. For some reason the coverage is decreased on this PR but all tests pass correctly.

Also, perhaps we could run a static server for tests to test this exact thing as well as these [other](https://github.com/lapwinglabs/x-ray/blob/master/test/xray_spec.js#L203) [tests](https://github.com/lapwinglabs/x-ray/blob/master/test/xray_spec.js#L265).

**Comment by GeoffreyEmery** [comment]
can we get this checked in?

**Comment by tribet84** [comment]
I tried your solution and still doesn't work for this example here: 

It works if you comment out the **uprice**. If you try to crawl then you get a nice "undefined is not a URL"

```

    x('https://www.simply.es/compra-online/especiales-2.html', {
      title: ['title'],
      items: x('.listing ul', [{
        main: '.descripcionProducto',
        link: '.descripcionProducto@href',
        uprice: x('.descripcionProducto a@href', '.precioKilo')
      }])
    })(function (err, obj) {
      if (err) { console.log(err); }
      console.log(obj);
    });
```

**Comment by Muscot** [comment]
Hi,
    
On the "link" it seems like descripcionProducto is a anchor and on the uprice you search for a anchor in ".descripcionProducto"?

Shouldn't it be something like this? couldn't access the www.simply.es url.

x('https://www.simply.es/compra-online/especiales-2.html', {
      title: ['title'],
      items: x('.listing ul', [{
        main: '.descripcionProducto',
        link: '.descripcionProducto@href',
        uprice: x('.descripcionProducto@href', '.precioKilo')
      }])
    })(function (err, obj) {
      if (err) { console.log(err); }
      console.log(obj);
    });

**Comment by tribet84** [comment]
Hi @Muscot ,
Excellent that works perfect! you made my day

Cheers,
r

**Comment by Muscot** [comment]
I'm glad I could help!
Cheers!

**Comment by tribet84** [comment]
so you think guys we can have this merged and published?

**Comment by GeoffreyEmery** [comment]
just used this on another project and it is still broken.. Do we just need to up this test coverage in order for this to get checked in?

**Comment by bisubus** [comment]
@matthewmueller Friendly ping. Would you consider merging this PR? It appears that the package is terribly broken for advanced usage since 2.0.3, see #189. I guess that fellow devs have no choice but to stick to forks or roll back to 2.0.2.

**Comment by Muscot** [comment]
I do not know have to merge my pull request to master? Tell me what I can do. It would be sad if this project do not move forward.

**Comment by darcyclarke** [comment]
Just going to also throw in a friendly reminder here. This is the only real game changer for me in terms of functionality compared to rolling my own implementation with request + cheerio. Having the ability to follow nested links is key for simple pagination/scraping implementations.

Can we push this through?

**Comment by matthewmueller** [comment]
sorry for the delay, thanks for your help @Muscot

**Comment by matthewmueller** [comment]
fixed in 2.3.1

**Pull request merged**
