### PR TITLE
Support x-ray-parse filters

### PR DESCRIPTION
**Pull request by fabien**
### Description

I noticed that x-ray-parse supports the notion of filters. This PR enables this functionality in Xray.

### Checklist

- [x] Code compiles correctly
- [x] Created tests which fail without the change (if possible)
- [x] All tests passing
- [x] Extended the README / documentation, if necessary
- [x] Added myself / the copyright holder to the AUTHORS file

### CODE REVIEW

**Comment by Kikobeats** [comment]
coverage decrease :joy:

**Comment by fabien** [comment]
A 0.1% decrease makes you cry? ;-)

**Comment by Kikobeats** [comment]
haha not really :smile: 

Extend readme part here is important, I understand that you are trying to mark the checklist until finally merge it?

**Comment by fabien** [comment]
I will see what I can do about the README. There's no AUTHORS file, is there?

**Comment by Kikobeats** [comment]
add you as contributor in the package.json http://browsenpm.org/package.json#contributors

**Comment by fabien** [comment]
Hi @Kikobeats is there anything withstanding this PR?

**Comment by Kikobeats** [comment]
@fabien sorry for the delay. Merged! I'm going to release a new minor version :-)

**Pull request merged**
