### PR TITLE
Add img[src] to absolute urls

### PR DESCRIPTION
**Pull request by cbou**

### CODE REVIEW

**Comment by MatthewMueller** [comment]
nice! what's the use case of this? We're using absolute urls to follow links IIRC

**Comment by cbou** [comment]
It's useful when you are looking for images with `src` starting with `/` and not `http`.

**Comment by MatthewMueller** [comment]
Ah, right. Any chance we could add the other ones now than? `script[src]`, `link[href]`, etc...

**Comment by cbou** [comment]
```
script[src]
link[href]
source[src] (for audio, video)
track[src] (for video)
img[src]
frame[src]
iframe[src]
```

Did I miss some of them ? Should we insert everything ?

**Comment by MatthewMueller** [comment]
probably good for now, there's probably a list in some repository somewhere

**Comment by cbou** [comment]
It should be ok. Sorry for non writing test. It try this but it didn't worked:

```javascript
  it('should support url without schemes', function(done) {
    var fixture = get('select-keys');
    xray('http://mat.io')
      .select(['link[ref="shortcut icon"][href]'])
      .run(function(err, arr) {
        if (err) return done(err);
        console.log(arr);
        done();
      })
  })
```

It outputs `[ undefined, undefined, undefined, undefined, undefined ]`.

**Comment by MatthewMueller** [comment]
I think it's related to this: https://github.com/lapwinglabs/x-ray/issues/7

**Comment by cbou** [comment]
Yeah works, but why?

**Comment by MatthewMueller** [comment]
The attribute parser needs some love

**Pull request merged**
