### PR TITLE
Do no error on trying to follow a non-url

### PR DESCRIPTION
**Pull request by gebrits**
Fixes problem discussed in #59

### CODE REVIEW

**Comment by federicomaffei** [comment]
@matthewmueller any chance for this PR to be reviewed/merged at some point? 
At the moment the scraper throws an error at every non-URL. 
A bit of a blocker when there is a quantity of links to follow and no specific need to validate all of them.
If you feel there is a need to add testing for this case I'm happy to expand this PR. Or even try to add URL parsing before throwing (in my case valid non-parsed URLs are rejected because of the lack of it).
Thanks.

**Comment by deathg0d** [comment]
+1 This seems like a much needed PR. Waiting for it on npm ;)

**Comment by matthewmueller** [comment]
awesome, thank you for your patience. I've merged this and bumped the version to 2.0.3

**Comment by federicomaffei** [comment]
@matthewmueller thanks! :+1:

**Comment by deathg0d** [comment]
@matthewmueller cool!!! thanks!

**Comment by deathg0d** [comment]
hi @matthewmueller , thanks for the update. I tried the update out and unfortunately it doesn't seem to be following any links at all. Were there changes made to other parts of the api too?

I don't know if I am doing this correctly, @federicomaffei , @gebrits could you please confirm if this update is working properly?

My code looks similar to the following:
```
x('http://....', 'div.somediv', [{
    title: 'a',
    description: x('a@href', 'div.article'),
}])(function(err, obj) {
    console.log(obj);
})
```
The above code is giving me object without the description field.

**Pull request merged**
